basePath: /
definitions:
  api.Data:
    properties:
      client:
        type: string
      psk:
        items:
          type: integer
        type: array
    type: object
  api.ResponseError:
    properties:
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is OpenAPI(2.0) for Bisquitt PSK
  title: Bisquitt PSK API
  version: "1.0"
paths:
  /clients/{id}:
    get:
      consumes:
      - application/json
      description: Get a client by ID
      parameters:
      - description: Client ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Data'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Get client
      tags:
      - clients
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
